---
test:
  load:
    begin_step: 1
    end_step: 10
    steps: 1
  gaze360:
    image: "data/Gaze360/Image"
    label: "data/Gaze360/Label"
  eth-mv:
    image: "data/eth-mv/Image"
    label: "data/eth-mv/Label_test"
  eth-mv-train:
    image: "data/eth-mv/Image"
    label: "data/eth-mv/Label_train"
  eth-mv100k:
    image: "data/eth-mv/Image"
    label: "data/eth-mv/Label100k_test"
  eth-mv100k-train:
    image: "data/eth-mv/Image"
    label: "data/eth-mv/Label100k_train"
dual:
  params:
    epoch: 10
    decay: 1
    decay_step: 2
  save:
    step: 1
  gaze360:
    image: "data/Gaze360/Image"
    label: "data/Gaze360/Label"
  eth-mv:
    image: "data/eth-mv/Image"
    label: "data/eth-mv/Label_test"
  eth-mv-train:
    image: "data/eth-mv/Image"
    label: "data/eth-mv/Label_train"
#  # Avoid using eth-mv100k for adaptation.
#  eth-mv100k:
#    image: "data/eth-mv/Image"
#    label: "data/eth-mv/Label100k_test"
#  eth-mv100k-train:
#    image: "data/eth-mv/Image"
#    label: "data/eth-mv/Label100k_train"
  pretrain_gaze360: "pretrain/Iter_20_gaze360.pt"
  pretrain_eth-mv100k-train: "pretrain/Iter_10_eth.pt"

